# Generated by Django 5.2.14 on 2026-05-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('imax', 'IMAX'), ('vip', 'VIP')], default='standard', max_length=50),
        ),
    ]
