# Generated by Django 5.2.14 on 2026-05-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_ticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Pay at Cinema'), ('vnpay', 'VNPay'), ('stripe', 'Stripe')], default='cash', max_length=20),
        ),
    ]
