# Generated by Django 5.2.14 on 2026-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_booking_hold_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtime',
            options={},
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.UniqueConstraint(fields=('room', 'start_time'), name='unique_showtime_room_start_time'),
        ),
    ]
